# mysql
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ms-buscador
    username: root
    password:
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
  application:
    name: ms-buscador

# Config de inst
server:
  port: 8086

## Configuracion del cliente de Eureka
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    hostname: ms-buscador