# mysql
spring:
  application:
    name: ms-buscador

# Config de inst
server:
  port: 8086

## Configuracion del cliente de Eureka
eureka:
  instance:
    preferIpAddress: false
    hostname: ${HOSTNAME:ms-buscador}
    non-secure-port-enabled: false
    secure-port-enabled: true
    non-secure-port: 80
    secure-port: 443
    
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}

##Elasticsearch config
elasticsearch:
  host: ${ELASTICSEARCH_HOST:unir-cluster-3229976543.us-east-1.bonsaisearch.net}
  credentials:
    user: ${ELASTICSEARCH_USER:4go8su7gxz}
    password: ${ELASTICSEARCH_PWD:owidctbvbi}
logging:
  level:
    tracer: TRACE